# -*- coding: utf-8 -*-
"""Finding_plain_text.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d4SUFg37yWL4xR5PPbuVkBxlfnUE46QN
"""

F = []
u=[]
ans=[]
def LFSR(x,y,z):
    for i in range(0,1088):
        t1 = (x >> 2) & 1
        x = (x>>1)|(((x&1)^((x>>1)&1))<<6)
        t2 = (y >> 3) & 1
        y = (y>>1)|(((y&1)^((y>>2)&1)^((y>>3)&1)^((y>>4)&1))<<7)
        t3 = (z >> 4) & 1
        z = (z >> 1) | (((z & 1) ^ ((z >> 4) & 1)) << 8)
        g=(((~t1) & (~t2)) | ((t2)&(~t3)) | ((t1)&(t3))) %2
        h = ((~t2) & (~t3) | ((t3) & (~t1)) | ((t1) & (t2))) %2
        l = ((~t2) & (~t3) | ((t3) & (t1)) | ((t2) & (~t1))) %2
        f = (t1 ^ t2 ^ t3 ^ g ^ h ^ l)
        F.append(f)

LFSR(62, 89, 122)
c=[0,0,1,0,1,0,1,1,0,0,0,0,1,0,1,1,1,1,0,1,1,0,1,0,0,0,1,0,0,0,1,0,1,0,0,1,0,1,1,0,1,1,1,0,0,1,1,0,0,1,0,0,1,0,0,0,0,1,1,1,1,1,1,1]

for i in range(1024,1088):
    a=F[i]
    u.append(a)

for i in range(0,64):
    b=u[i]^c[i]
    ans.append(b)
print(ans)